#!/bin/bash

if [ -z "${HOST_USER}" ]; then
  echo "ERROR: We need USER to be set!"; exit 100
fi

if [ -z "${HOST_UID}" ]; then
    echo "ERROR: We need HOST_UID be set" ; exit 100
fi

if [ -z "${HOST_GID}" ]; then
    echo "ERROR: We need HOST_GID be set" ; exit 100
fi

useradd ${HOST_USER} --shell /bin/bash --create-home \
	--uid ${HOST_UID} --gid ${HOST_GID} > /dev/null 2>&1

echo 'ALL ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers

chown -R ${HOST_UID}:${HOST_GID} /home/${USER}

# switch to current user
su "${HOST_USER}"

# enter to shell
exec /bin/bash
